version: '3.7'
services:
  mongoProd:
    image: mongo:latest
    container_name: 'mongo-prod-container'
    environment:
      MONGO_INITDB_DATABSE: my-retail-db
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      DB_USER_PASSWORD: ${PROD_DB_USER_PASSWORD}
      DB_USER_USERNAME: ${PROD_DB_USER_USERNAME}
    ports:
      - 27000:27017
    volumes:
      - ./docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  mongoDev:
    image: mongo:latest
    container_name: 'mongo-dev-container'
    environment:
      MONGO_INITDB_DATABSE: my-retail-db
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      DB_USER_PASSWORD: ${DEV_DB_USER_PASSWORD}
      DB_USER_USERNAME: ${DEV_DB_USER_USERNAME}
    ports:
      - 27001:27017
    volumes:
      - ./docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  admin:
    image: dockette/adminer:full-php5
    restart: always
    ports:
      - "5401:80"