## --------------------------------------------------
## | PRODUCTION Properties |
## --------------------------------------------------

# db password: target$redsky
# db username: db-prod-user
# mongodb+srv://db-prod-user:target$redsky@cluster0.cdd4o.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

spring:
  data:
    mongodb:
      uri: mongodb+srv://${ATLAS_DB_USER}:${ATLAS_DB_PASSWORD}@cluster0.cdd4o.mongodb.net/${ATLAS_DB}?retryWrites=true&w=majority
