## --------------------------------------------------
## | PRODUCTION Properties |
## --------------------------------------------------

spring:
  data:
    mongodb:
      uri: mongodb+srv://${ATLAS_DB_USER}:${ATLAS_DB_PASSWORD}@cluster0.cdd4o.mongodb.net/${ATLAS_DB}?retryWrites=true&w=majority
