## --------------------------------------------------
## | DEVELOPMENT Properties |
## --------------------------------------------------

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27001
      database: my-retail-db
      username: admin
      password: admin