## --------------------------------------------------
## | PRODUCTION Properties |
## --------------------------------------------------

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27000
      database: my-retail-db
      username: admin
      password: admin