## --------------------------------------------------
## | PRODUCTION Properties |
## --------------------------------------------------

# db password: target$redsky
# db username: db-prod-user
# mongodb+srv://db-prod-user:target$redsky@cluster0.cdd4o.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

spring:
  data:
    mongodb:
      uri: mongodb+srv://db-prod-user:target$redsky@cluster0.cdd4o.mongodb.net/my-retail-db?retryWrites=true&w=majority
