## --------------------------------------------------
## | Properties that are the same across DEV & PROD |
## --------------------------------------------------

spring:
  application.name: My Retail Server
  profiles.active: @activatedProperties@

server:
  port: 8080

